apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limit-range
  namespace: exam
spec:
  limits:
  - type: Container  # Type de limite pour le conteneur individuel
    max:
      cpu: "2"            # Limite maximale de CPU par conteneur
      memory: 4Gi         # Limite maximale de mémoire par conteneur
    min:
      cpu: "100m"         # Limite minimale de CPU par conteneur
      memory: 100Mi       # Limite minimale de mémoire par conteneur