apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  serviceAccountName: mon-service-account  # Utiliser le ServiceAccount que vous avez créé
  containers:
  - name: test-container
    image: nginx
    command: ["sleep", "3600"]  # Exemple de commande pour garder le pod actif