apiVersion: apps/v1  # Version de l'API Kubernetes
kind: Deployment  # Type de ressource, un déploiement
metadata:
  name: tutorial-app-mysql-health  # Nom du déploiement
  namespace: exam  # Espace de noms où le déploiement est créé
spec:
  selector:
    matchLabels:
      app: tutorial-app-mysql-health  # Sélecteur pour trouver les pods associés à ce déploiement
  replicas: 1  # Nombre de répliques pour le déploiement
  template:
    metadata:
      labels:
        app: tutorial-app-mysql-health  # Étiquette pour l'application dans le template du déploiement
    spec:
      containers:
      - name: tutorial-app-mysql  # Nom du conteneur
        image: mysql:5.6  # Image Docker utilisée pour le conteneur MySQL
        ports:
        - containerPort: 3306  # Port exposé par le conteneur MySQL
        livenessProbe:  # Vérification de la disponibilité du conteneur
          tcpSocket:
            port: 3306  # Port à tester pour la sonde de vivacité
          initialDelaySeconds: 15  # Délai avant la première vérification
          periodSeconds: 10  # Fréquence des vérifications
        readinessProbe:  # Vérification de la préparation du conteneur
          tcpSocket:
            port: 3306  # Port à tester pour la sonde de préparation
          initialDelaySeconds: 20  # Délai avant la première vérification
          periodSeconds: 10  # Fréquence des vérifications
        startupProbe:  # Vérification du démarrage du conteneur
          tcpSocket:
            port: 3306  # Port à tester pour la sonde de démarrage
          failureThreshold: 30  # Nombre maximum de tentatives de vérification en échec
          periodSeconds: 10  # Fréquence des vérifications
